---
title: "cleaned_df"
author: "Jodie"
date: "2024-07-08"
output: html_document
---


```{r}
#colnames(selected_data)
```

## R Markdown

```{r}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(knitr)
library(broom)


```


```{r}
health_data <- read.csv("data/analytic_data2024.csv") |> 
  slice(-1) |>
  clean_names()


selected_data <- health_data |> 
  select(
    state_fips_code, county_fips_code, county_clustered_yes_1_no_0, state_abbreviation, name, x5_digit_fips_code,
    drug_overdose_deaths_raw_value, 
    drug_overdose_deaths_numerator, 
    drug_overdose_deaths_denominator,
    alcohol_impaired_driving_deaths_raw_value, alcohol_impaired_driving_deaths_numerator, alcohol_impaired_driving_deaths_denominator,
    unemployment_raw_value, income_inequality_raw_value, high_school_completion_raw_value, 
    adult_smoking_raw_value, excessive_drinking_raw_value, median_household_income_raw_value,
    some_college_raw_value, children_in_poverty_raw_value, children_in_single_parent_households_raw_value,
    social_associations_raw_value, x_below_18_years_of_age_raw_value, 
    x_65_and_older_raw_value, x_non_hispanic_black_raw_value, 
    x_american_indian_or_alaska_native_raw_value, x_asian_raw_value, 
    x_native_hawaiian_or_other_pacific_islander_raw_value, x_hispanic_raw_value, 
    x_non_hispanic_white_raw_value, x_not_proficient_in_english_raw_value,
    x_female_raw_value, x_rural_raw_value, long_commute_driving_alone_raw_value, population_raw_value, traffic_volume_raw_value, 
    homicides_raw_value, homicides_numerator, homicides_denominator,
    suicides_raw_value, suicides_numerator, suicides_denominator,
    disconnected_youth_raw_value, disconnected_youth_numerator, 
    disconnected_youth_denominator
  )

# Convert relevant columns to numeric
selected_data <- selected_data |> 
  mutate(across(
    starts_with("drug_overdose_deaths") | starts_with("alcohol_impaired_driving_deaths") |
    starts_with("unemployment_raw_value") | starts_with("income_inequality_raw_value") | 
    starts_with("high_school_completion_raw_value") | starts_with("adult_smoking_raw_value") |
    starts_with("excessive_drinking_raw_value") | starts_with("median_household_income_raw_value") |
    starts_with("some_college_raw_value") | starts_with("children_in_poverty_raw_value") | 
    starts_with("children_in_single_parent_households_raw_value") | 
    starts_with("social_associations_raw_value") | starts_with("x_below_18_years_of_age_raw_value") | 
    starts_with("x_65_and_older_raw_value") | starts_with("x_non_hispanic_black_raw_value") | 
    starts_with("x_american_indian_or_alaska_native_raw_value") | starts_with("x_asian_raw_value") | 
    starts_with("x_native_hawaiian_or_other_pacific_islander_raw_value") | starts_with("x_hispanic_raw_value") | 
    starts_with("x_non_hispanic_white_raw_value") | starts_with("x_not_proficient_in_english_raw_value") | 
    starts_with("x_female_raw_value") | starts_with("x_rural_raw_value") | starts_with("population_raw_value") | starts_with("long_commute_driving_alone_raw_value") | starts_with("traffic_volume_raw_value") |
starts_with("homicides") | starts_with("suicides") |
  starts_with("disconnected"),
    as.numeric
  )) 
#glimpse(health_data)

# add population density column
# GEOID is a unique county and corresponds to x5_digit_fips_code in health_data
library(tigris)
us_counties <- counties(cb = TRUE)
census_df <- us_counties |>
  select(x5_digit_fips_code=GEOID, land_area=ALAND)

# Inner join: only rows with matching x5_digit_fips_code will be included
new_sel <- merge(selected_data, census_df, by = "x5_digit_fips_code")

new_df <- new_sel |>
  mutate(land_area_km = land_area / 1000000) |>
  mutate(pop_den = population_raw_value / land_area_km)

glimpse(new_df) # has population density and land area_km
```


```{r}
new_df$`Income level` <- cut(new_df$median_household_income_raw_value,
                                  breaks = c(-Inf, 52610, 60986, 70897, Inf),
                                  labels = c("Low", "Lower-Middle", "Upper-Middle", "High"),
                                  right = TRUE, na.rm=TRUE)

new_df <- new_df %>%
  rename(
    FIPS_5 = x5_digit_fips_code,
    State_FIPS = state_fips_code,
    County_FIPS = county_fips_code,
    Clustered = county_clustered_yes_1_no_0,
    State_Abbrev = state_abbreviation,
    County_Name = name,
    OD_Deaths_Raw = drug_overdose_deaths_raw_value,
    OD_Deaths_Num = drug_overdose_deaths_numerator,
    OD_Deaths_Denom = drug_overdose_deaths_denominator,
    Alcohol_Deaths_Raw = alcohol_impaired_driving_deaths_raw_value,
    Alcohol_Deaths_Num = alcohol_impaired_driving_deaths_numerator,
    Alcohol_Deaths_Denom = alcohol_impaired_driving_deaths_denominator,
    Unemployment_Rate = unemployment_raw_value,
    Income_Inequality = income_inequality_raw_value,
    HS_Completion_Rate = high_school_completion_raw_value,
    Adult_Smoking_Rate = adult_smoking_raw_value,
    Excessive_Drinking_Rate = excessive_drinking_raw_value,
    Median_HH_Income = median_household_income_raw_value,
    Some_College_Rate = some_college_raw_value,
    Child_Poverty_Rate = children_in_poverty_raw_value,
    Single_Parent_Rate = children_in_single_parent_households_raw_value,
    Social_Assoc_Rate = social_associations_raw_value,
    Age_Under_18 = x_below_18_years_of_age_raw_value,
    Age_65_Plus = x_65_and_older_raw_value,
    NH_Black_Rate = x_non_hispanic_black_raw_value,
    AI_AN_Rate = x_american_indian_or_alaska_native_raw_value,
    Asian_Rate = x_asian_raw_value,
    NHPI_Rate = x_native_hawaiian_or_other_pacific_islander_raw_value,
    Hispanic_Rate = x_hispanic_raw_value,
    NH_White_Rate = x_non_hispanic_white_raw_value,
    English_Proficiency = x_not_proficient_in_english_raw_value,
    Female_Rate = x_female_raw_value,
    Rural_Rate = x_rural_raw_value,
    Long_Commute_Rate = long_commute_driving_alone_raw_value,
    Population = population_raw_value,
    Traffic_Volume = traffic_volume_raw_value,
    Land_Area_sqm = land_area,
    Geometry = geometry,
    Land_Area_km = land_area_km,
    Pop_Density = pop_den
  ) |> 
    drop_na(Excessive_Drinking_Rate, Alcohol_Deaths_Raw)


str(new_df)
```

# only for alcohol_impaired_rates
```{r}
# go back on this....based on akshay's comments 
# include entries with at least 3000
fifth_percentile <- quantile(new_df$population_raw_value, probs = 0.05)
print(fifth_percentile) # 2672

new_data <- new_df %>%
  filter(Population > 3000)


names(new_data)


# use new_data for alcohol_impaired death rates
# use new_df for drug overdose 
```

<<<<<<< HEAD
# add homicide (social--community safety), suicide (social--community safety), disconnected youths (social-education)
```{r}
```
=======
```{r}
write.csv(new_data, "alcohol_df.csv")
write.csv(new_df, "drugs_df.csv")
```

>>>>>>> 9f5df130596e62a7852c6a4915d0664f1a083b3f
