

***READ ME******
THIS TAKES A LONG TIME TO LOAD SO ONLY LOAD WHEN NECCESAARY!!!!!!!



```{r}
library(tidyverse)
library(readr)
library(MASS)

```

```{r}
# Read and rename the dataset
imputed_data <- read_csv("imputed_data.csv") %>%
  rename(
    ID = ...1,
    Drug_Overdose_Deaths = drug_overdose_deaths_raw_value,
    Alcohol_Impaired_Driving_Deaths = alcohol_impaired_driving_deaths_raw_value,
    Unemployment_Rate = unemployment_raw_value,
    Income_Inequality = income_inequality_raw_value,
    Highschool_Comp_Rate = high_school_completion_raw_value,
    Adult_Smoking_Rate = adult_smoking_raw_value,
    Excessive_Drinking_Rate = excessive_drinking_raw_value,
    Median_House_Income = median_household_income_raw_value,
    College_Education_Rate = some_college_raw_value,
    Children_In_Poverty = children_in_poverty_raw_value,
    Single_Parent_House = children_in_single_parent_households_raw_value,
    Social_Associations = social_associations_raw_value,
    Pop_Under_18 = x_below_18_years_of_age_raw_value,
    Pop_Over_65 = x_65_and_older_raw_value,
    NH_Black = x_non_hispanic_black_raw_value,
    American_Or_Alaska_Native = x_american_indian_or_alaska_native_raw_value,
    Asian_Pop = x_asian_raw_value,
    Pacific_Islander = x_native_hawaiian_or_other_pacific_islander_raw_value,
    Hispanic_Pop = x_hispanic_raw_value,
    NH_White = x_non_hispanic_white_raw_value,
    English_Profic = x_not_proficient_in_english_raw_value,
    Female_Pop = x_female_raw_value,
    Rural_Pop = x_rural_raw_value
  )
  

```


```{r}

# Example model for Drug Overdose Deaths
model1 <- glm(Drug_Overdose_Deaths ~ Unemployment_Rate + Income_Inequality + Highschool_Comp_Rate + 
              Adult_Smoking_Rate + Excessive_Drinking_Rate + Median_House_Income + College_Education_Rate + 
              Children_In_Poverty + Single_Parent_House + Social_Associations + Pop_Under_18 + Pop_Over_65 + 
              NH_Black + American_Or_Alaska_Native + Asian_Pop + Pacific_Islander + Hispanic_Pop + 
              NH_White + English_Profic + Female_Pop + Rural_Pop, data = imputed_data, family = "poisson")
```


```{r}
# Compute AIC and BIC for the model
aic1 <- AIC(model1)
bic1 <- BIC(model1)

# Print AIC and BIC
print(paste("AIC for Model 1:", aic1))
print(paste("BIC for Model 1:", bic1))

```


```{r}
# Stepwise model selection based on BIC
stepwise_model <- stepAIC(model1, direction = "both", k = log(nrow(imputed_data)), trace = FALSE)

# Final model summary
summary(stepwise_model)

```

