---
title: "Drugs"
author: "Dennis Campoverde-Lema"
date: "2024-06-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(kableExtra)
library(broom)
library(glmnet)
library(caret)
library(corrr)
library(ggcorrplot)
library(corrplot)
library(ggdendro)
library(ggplot2)
library(factoextra)


```


```{r}
# Read and rename data
imputed_data <- read_csv("imputed_data.csv") %>%
  rename(
    ID = ...1,
    Drug_Overdose_Deaths = drug_overdose_deaths_raw_value,
    Alcohol_Impaired_Driving_Deaths = alcohol_impaired_driving_deaths_raw_value,
    Unemployment_Rate = unemployment_raw_value,
    Income_Inequality = income_inequality_raw_value,
    Highschool_Comp_Rate = high_school_completion_raw_value,
    Adult_Smoking_Rate = adult_smoking_raw_value,
    Excessive_Drinking_Rate = excessive_drinking_raw_value,
    Median_House_Income = median_household_income_raw_value,
    College_Education_Rate = some_college_raw_value,
    Children_In_Poverty = children_in_poverty_raw_value,
    Single_Parent_House = children_in_single_parent_households_raw_value,
    Social_Associations = social_associations_raw_value,
    Pop_Under_18 = x_below_18_years_of_age_raw_value,
    Pop_Over_65 = x_65_and_older_raw_value,
    NH_Black = x_non_hispanic_black_raw_value,
    American_Or_Alaska_Native = x_american_indian_or_alaska_native_raw_value,
    Asian_Pop = x_asian_raw_value,
    Pacific_Islander = x_native_hawaiian_or_other_pacific_islander_raw_value,
    Hispanic_Pop = x_hispanic_raw_value,
    NH_White = x_non_hispanic_white_raw_value,
    English_Profic = x_not_proficient_in_english_raw_value,
    Female_Pop = x_female_raw_value,
    Rural_Pop = x_rural_raw_value
  )

```


```{r}
# Fit linear model for drug overdose deaths
model_drug <- lm(Drug_Overdose_Deaths ~ ., data = imputed_data)
summary_drug <- summary(model_drug)
significant_vars_drug <- names(which(summary_drug$coefficients[,4] < 0.05))
significant_vars_drug <- significant_vars_drug[significant_vars_drug != "(Intercept)"]

print(significant_vars_drug)


```

```{r}
# Fit linear model for drug overdose deaths
model_drug <- lm(Drug_Overdose_Deaths ~ ., data = imputed_data)
summary_drug <- summary(model_drug)
significant_vars_drug <- names(which(summary_drug$coefficients[,4] < 0.05))
significant_vars_drug <- significant_vars_drug[significant_vars_drug != "(Intercept)"]

print(significant_vars_drug)


```

```{r}

# Data selection and correlation analysis for alcohol related data
selected_data_a <- imputed_data %>%
  select(Alcohol_Impaired_Driving_Deaths, Adult_Smoking_Rate, Pop_Under_18,
         Female_Pop, Unemployment_Rate, Excessive_Drinking_Rate, Pop_Over_65)

cor_matrix <- cor(selected_data_a)
corrplot(cor_matrix, method = "color", tl.col = "black", tl.cex = 0.8)
cor_dist_matrix <- as.dist(1 - abs(cor_matrix))
hc <- hclust(cor_dist_matrix, method = "complete")
ggdendrogram(hc, rotate = TRUE, size = 2) +
  labs(title = "Dendrogram of Variables Using Correlation Matrix",
       x = "Variables",
       y = "Height")

```



```{r}
# Data selection and correlation analysis for drug related data
selected_data_d <- imputed_data %>%
  select(Drug_Overdose_Deaths, Adult_Smoking_Rate, Income_Inequality,
         Excessive_Drinking_Rate, Median_House_Income, College_Education_Rate,
         Single_Parent_House, Pop_Under_18, NH_White)

cor_matrix <- cor(selected_data_d)
corrplot(cor_matrix, method = "color", tl.col = "black", tl.cex = 0.8)
cor_dist_matrix <- as.dist(1 - abs(cor_matrix))
hc <- hclust(cor_dist_matrix, method = "complete")
ggdendrogram(hc, rotate = TRUE, size = 2) +
  labs(title = "Dendrogram of Variables Using Correlation Matrix",
       x = "Variables",
       y = "Height")


```

```{r}
# PCA analysis
pca_result <- prcomp(selected_data_d, scale. = TRUE)
fviz_pca_biplot(pca_result, label = "var",
                alpha.ind = 0.25, alpha.var = 0.75,
                col.var = "purple", repel = TRUE) +
  labs(title = "PCA Biplot",
       subtitle = "Correlation of Variables with Drug Overdose Deaths",
       x = "Principal Component 1",
       y = "Principal Component 2") +
  theme_minimal() +
  theme(plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5))

```

