```{r}
library(tidyverse)
library(glmnet)
library(corrplot)
library(vip)
library(forcats)

```


```{r}
health <- read_csv("../data/final_data.csv")

str(health)
```


```{r}
health <- health |> 
  select(-name) |>
  filter(population > 3000) |> 
  mutate(across(everything(), ~ifelse(is.na(.), mean(., na.rm = TRUE), .)))
head(health)


# Prepare the predictors and response
x <- as.matrix(health |>  select(-alcohol_impaired_driving_deaths))
y <- health$alcohol_impaired_driving_deaths

```
```{r}
healtha_lm <- lm(alcohol_impaired_driving_deaths ~ ., data = health)
library(broom)
healtha_lm |> 
  tidy() |> 
  mutate(term = fct_reorder(term, estimate)) |> 
  ggplot(aes(x = estimate, y = term, 
             fill = estimate > 0)) +
  geom_col(color = "white", show.legend = FALSE) +
  scale_fill_manual(values = c("darkred", "darkblue"))
```


```{r}
# Perform cross-validation to find the optimal lambda for Lasso
lasso_cv <- cv.glmnet(x, y, alpha = 1)

# Fit the final Lasso regression model using the optimal lambda
lasso_final <- glmnet(x, y, alpha = 1, lambda = lasso_cv$lambda.min)

plot(lasso_cv, xvar = "lambda", label = TRUE) |> 
title("lasso Regression Coefficients")
```


```{r}
# Extract the coefficients at the optimal lambda
lasso_coef <- coef(lasso_final)

lasso_coef
# Convert the coefficients matrix to a tibble and filter out zero coefficients
tidy_lasso_coef <- as_tibble(as.matrix(lasso_coef), rownames = "term") %>%
  filter(term != "(Intercept)")

# Visualize the coefficients
tidy_lasso_coef %>%
  mutate(term = fct_reorder(term, s0)) %>%
  ggplot(aes(x = s0, y = term, fill = s0 > 0)) +
  geom_col(color = "white", show.legend = FALSE) +
  scale_fill_manual(values = c("darkred", "darkblue")) +
  labs(title = "Lasso Regression Coefficients",
       x = "Coefficient Estimate",
       y = "Predictor")

```

