```{r}
library(tidyverse)
library(randomForest)
library(glmnet)
library(VIM)
```


```{r}
health_tt <- read_csv("../data/final_data.csv")


health_tt <- health_tt |> 
  select(-name, -...1, -population, -alcohol_impaired_driving_deaths, -homicides, -excessive_drinking) 

health_tt |>  summarise(across(everything(), ~ sum(is.na(.))))


health_tt <- na.omit(health_tt)
```


```{r}



set.seed(101)
k <- 5
health_tt <- health_tt |>
  mutate(test_fold = sample(rep(1:k, length.out = n())))
```


```{r}
get_test_pred <- function(k) {
  test_data <- health_tt |>  filter(test_fold == k)                     # get test and training data
  train_data <- health_tt |>  filter(test_fold != k)
  test_x <- as.matrix(select(test_data, -drug_overdose_deaths))            # get test and training matrices
  train_x <- as.matrix(select(train_data, -drug_overdose_deaths))
  
  lm_fit <- lm(drug_overdose_deaths ~ ., data = train_data)                  # fit models to training data
  ridge_fit <- cv.glmnet(train_x, train_data$drug_overdose_deaths, alpha = 0)
  lasso_fit <- cv.glmnet(train_x, train_data$drug_overdose_deaths, alpha = 1)
  enet_fit <- cv.glmnet(train_x, train_data$drug_overdose_deaths, alpha = 0.5)
  rf_fit <- randomForest(drug_overdose_deaths ~ ., data = train_data, importance = TRUE)
  
  tibble(lm_pred = predict(lm_fit, newdata = test_data),              # return test results
         ridge_pred = as.numeric(predict(ridge_fit, newx = test_x)),
         lasso_pred = as.numeric(predict(lasso_fit, newx = test_x)),
         enet_pred = as.numeric(predict(enet_fit, newx = test_x)),
         rf_pred = predict(rf_fit, newdata = test_data),
         test_actual = test_data$drug_overdose_deaths,
         test_fold = k)
}
```


```{r}
#health_tt <- kNN(health_tt, k = 5, imp_var = FALSE)

test_pred_all <- map(1:k, get_test_pred) |> 
  bind_rows()
```


```{r}
test_pred_all |>
  pivot_longer(lm_pred:rf_pred, 
               names_to = "type", 
               values_to = "test_pred") |>
  group_by(type, test_fold) |>
  summarize(
    rmse = sqrt(mean((test_actual - test_pred)^2))
  ) |> 
  ggplot(aes(x = type, y = rmse)) + 
  geom_point(size = 4) +
  stat_summary(fun = mean, geom = "point", 
               color = "red", size = 4) + 
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               color = "red", width = 0.2)
```

